"""
SatTope — Lightning payment layer for Argentine merchants.

Flow:
1. Customer pays Lightning invoice generated by phoenixd
2. Sats land in merchant's phoenixd wallet
3. Merchant decides when to convert sats → USDT via WapuPay
4. Merchant withdraws USDT → ARS → Mercado Pago when ready
"""

import json
import logging
import os
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from pydantic import BaseModel

from phoenixd import (create_phoenixd_invoice, get_phoenixd_balance,
                      get_phoenixd_invoice, list_phoenixd_payments,
                      pay_phoenixd_invoice)
from wapu import create_lightning_invoice, get_transaction, get_transactions, get_wapu_home

load_dotenv()

logging.basicConfig(level=logging.INFO, format="%(asctime)s  %(levelname)s  %(message)s")
logger = logging.getLogger(__name__)

WAPU_WITHDRAW_ALIAS = os.getenv("WAPU_WITHDRAW_ALIAS", "")
WITHDRAWALS_FILE = Path("data/withdrawals.json")

app = FastAPI(
    title="SatTope",
    description="Lightning payment layer for Argentine merchants.",
    version="2.0.0"
)
app.mount("/static", StaticFiles(directory="static"), name="static")
templates = Jinja2Templates(directory="templates")


# --- Local storage helpers ---

def _load_withdrawals() -> list:
    if not WITHDRAWALS_FILE.exists():
        return []
    with open(WITHDRAWALS_FILE) as f:
        return json.load(f)


def _save_withdrawals(withdrawals: list):
    WITHDRAWALS_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(WITHDRAWALS_FILE, "w") as f:
        json.dump(withdrawals, f, indent=2)


# --- Request models ---

class PaymentRequest(BaseModel):
    amount_sat: int
    description: str = "Payment"


class ConvertRequest(BaseModel):
    amount_sat: int


class WithdrawRequest(BaseModel):
    amount_usdt: float
    alias: str = ""


# --- Store pages ---

@app.get("/", response_class=HTMLResponse)
async def homepage(request: Request):
    return templates.TemplateResponse(request, "index.html")


@app.get("/product", response_class=HTMLResponse)
async def product_page(request: Request):
    return templates.TemplateResponse(request, "product.html")


@app.get("/checkout", response_class=HTMLResponse)
async def checkout_page(request: Request):
    return templates.TemplateResponse(request, "checkout.html")


@app.get("/confirmation", response_class=HTMLResponse)
async def confirmation_page(request: Request):
    return templates.TemplateResponse(request, "confirmation.html")


@app.get("/plugin", response_class=HTMLResponse)
async def plugin_page(request: Request):
    return templates.TemplateResponse(request, "plugin.html")


# --- Payment endpoints ---

@app.post("/create-payment")
async def create_payment(payment: PaymentRequest):
    """Creates a phoenixd Lightning invoice for the checkout page."""
    try:
        invoice = await create_phoenixd_invoice(payment.amount_sat, payment.description)
        bolt11 = invoice.get("serialized")
        payment_hash = invoice.get("paymentHash", "")
        logger.info(f"Invoice created: {payment_hash[:16]}... for {payment.amount_sat} sats")
        return {
            "bolt11": bolt11,
            "payment_hash": payment_hash,
            "amount_sat": payment.amount_sat,
        }
    except Exception as e:
        logger.error(f"Failed to create invoice: {e}")
        raise HTTPException(status_code=502, detail=str(e))


@app.get("/check-payment/{payment_hash}")
async def check_payment(payment_hash: str):
    """Poll phoenixd for invoice settlement."""
    try:
        invoice = await get_phoenixd_invoice(payment_hash)
        paid = invoice.get("isPaid", False)
        return {"paid": paid, "invoice": invoice}
    except Exception as e:
        logger.warning(f"Payment check failed: {e}")
        return {"paid": False, "error": str(e)}


# --- Dashboard ---

@app.get("/api/dashboard")
async def dashboard():
    """Aggregates phoenixd payments, WapuPay balance, and withdrawal history."""

    # phoenixd balance
    try:
        bal = await get_phoenixd_balance()
        balance_sat = bal.get("local", 0)
    except Exception:
        balance_sat = 0

    # phoenixd payment history
    try:
        raw = await list_phoenixd_payments(50)
        payments = []
        for p in raw:
            if p.get("isPaid"):
                ts = p.get("completedAt") or p.get("createdAt") or 0
                payments.append({
                    "payment_hash": p.get("paymentHash", ""),
                    "amount_sat": p.get("receivedSat", 0),
                    "description": p.get("description", "—"),
                    "date": datetime.fromtimestamp(ts / 1000).strftime("%Y-%m-%d %H:%M") if ts else "—",
                })
    except Exception:
        payments = []

    # WapuPay balance + rates
    try:
        home = await get_wapu_home()
        usdt_balance = home.get("usdt_balance", 0)
        combined_balance_ars = home.get("combined_balance", 0)
        rates = {r["pair"]: r for r in home.get("rates", [])}
    except Exception:
        usdt_balance = 0
        combined_balance_ars = 0
        rates = {}

    # WapuPay conversion history
    try:
        wapu_txs = await get_transactions()
        if isinstance(wapu_txs, dict):
            wapu_txs = wapu_txs.get("transactions", []) or wapu_txs.get("items", []) or []
    except Exception:
        wapu_txs = []

    # Mercado Pago withdrawals (local demo records)
    withdrawals = _load_withdrawals()

    return {
        "balance_sat": balance_sat,
        "usdt_balance": usdt_balance,
        "combined_balance_ars": combined_balance_ars,
        "rates": rates,
        "payments": payments,
        "wapu_transactions": wapu_txs,
        "withdrawals": withdrawals,
    }


# --- Convert sats → USDT ---

@app.post("/convert-to-usdt")
async def convert_to_usdt(body: ConvertRequest):
    """
    Creates a WapuPay Lightning invoice and pays it from phoenixd.
    Sats leave the merchant's Phoenix wallet → land in WapuPay → auto-convert to USDT.
    """
    try:
        wapu_invoice = await create_lightning_invoice(body.amount_sat)
        bolt11 = (
            wapu_invoice.get("lnurl_pr_invoice") or
            wapu_invoice.get("payment_request") or
            wapu_invoice.get("bolt11")
        )
        tx_id = wapu_invoice.get("transaction_id") or wapu_invoice.get("id")
        logger.info(f"WapuPay invoice created for {body.amount_sat} sats, tx={tx_id}")

        result = await pay_phoenixd_invoice(bolt11)
        logger.info(f"phoenixd paid WapuPay invoice: {result}")

        return {"status": "sent", "amount_sat": body.amount_sat, "wapu_tx_id": tx_id}
    except Exception as e:
        logger.error(f"Conversion failed: {e}")
        raise HTTPException(status_code=502, detail=str(e))


@app.get("/check-conversion/{tx_id}")
async def check_conversion(tx_id: str):
    """Poll WapuPay to confirm the sats → USDT conversion settled."""
    try:
        tx = await get_transaction(tx_id)
        status = tx.get("status", "").upper()
        settled = status in ("COMPLETED", "DONE", "PAID", "SUCCESS")
        usdt_amount = float(tx.get("payment_amount") or 0) if settled else 0
        return {"settled": settled, "status": status, "usdt_amount": usdt_amount}
    except Exception as e:
        return {"settled": False, "status": "ERROR", "error": str(e)}


# --- Mercado Pago withdrawal (demo) ---

@app.post("/withdraw-mercadopago")
async def withdraw_mercadopago(body: WithdrawRequest):
    """Demo endpoint — records a Mercado Pago withdrawal as pending."""
    withdrawals = _load_withdrawals()
    withdrawal = {
        "id": os.urandom(8).hex(),
        "amount_usdt": body.amount_usdt,
        "alias": body.alias or WAPU_WITHDRAW_ALIAS or "—",
        "date": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "status": "Pending"
    }
    withdrawals.append(withdrawal)
    _save_withdrawals(withdrawals)
    logger.info(f"Withdrawal recorded: {body.amount_usdt} USDT → {withdrawal['alias']}")
    return {"status": "pending", "withdrawal": withdrawal}
